#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

$service = new \Sirprize\Basecamp\Cli($config);
$service->setLog($log);

$persons = $service->getPersonsInstance();
$persons->startAll();

if($persons->getResponse()->isError())
{
	die("Error\n");
}
	
foreach($persons as $person)
{
    // the username will only be shown if the current user has admin privileges
	print $person->getFirstname().' '.$person->getLastname().' ('.$person->getUsername().")\n";
}