#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);

require_once 'Sirprize/Basecamp/Person/Collection/Observer/Stout.php';
$collectionObserverStout = new \Sirprize\Basecamp\Person\Collection\Observer\Stout();

require_once 'Sirprize/Basecamp/Person/Collection/Observer/Log.php';
$collectionObserverLog = new \Sirprize\Basecamp\Person\Collection\Observer\Log();
$collectionObserverLog->setLog($log);

$persons = $basecamp->getPersonCollectionInstance();
$persons->attachObserver($collectionObserverStout);
$persons->attachObserver($collectionObserverLog);
$persons->startAll();

if($persons->getResponse()->isError())
{
	die('Error');
}
	
foreach($persons as $person)
{
	print "id: ".$person->getId()."\n";
	print "--------------------------\n";
}