#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

$basecamp = new \Sirprize\Basecamp\Cli($config);
$basecamp->setLog($log);

$projectId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_PROJECT_ID);

$persons = $basecamp->getPersonsInstance();
$persons->startAllByProjectId($projectId);

if($persons->getResponse()->isError())
{
	die("Error\n");
}
	
foreach($persons as $person)
{
	print $person->getFirstname().' '.$person->getLastname().' - '.$person->getId()."\n";
}