#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$personId = new Id(BASECAMP_EXAMPLE_USER_ID);

$persons = $service->getPersonsInstance();
$person = $persons->startById($personId);

if($person === null)
{
    die("Not found\n");
}

if($persons->getResponse()->isError())
{
    die("Error\n");
}

print "is administrator: ".$person->getIsAdministrator()."\n";
print "client id: ".$person->getClientId()."\n";
print "created at: ".$person->getCreatedAt()."\n";
print "is deleted: ".$person->getIsDeleted()."\n";
print "has access to new projects: ".$person->getHasAccessToNewProjects()."\n";
print "id: ".$person->getId()."\n";
print "im handle: ".$person->getImHandle()."\n";
print "im service: ".$person->getImService()."\n";
print "phone number fax: ".$person->getPhoneNumberFax()."\n";
print "phone number home: ".$person->getPhoneNumberHome()."\n";
print "phone number mobile: ".$person->getPhoneNumberMobile()."\n";
print "phone number office: ".$person->getPhoneNumberOffice()."\n";
print "phone number ext: ".$person->getPhoneNumberOfficeExt()."\n";
print "title: ".$person->getTitle()."\n";
print "updated at: ".$person->getUpdatedAt()."\n";
print "uuid: ".$person->getUuid()."\n";
print "firstname: ".$person->getFirstname()."\n";
print "lastname: ".$person->getLastname()."\n";
print "company id: ".$person->getCompanyId()."\n";
print "username: ".$person->getUsername()."\n";
print "email address: ".$person->getEmailAddress()."\n";
print "avatar url: ".$person->getAvatarUrl()."\n";