#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$persons = $service->getPersonsInstance();
$persons->startAll();

if($persons->getResponse()->isError())
{
    die("Error\n");
}

foreach($persons as $person)
{
    // the username will only be shown if the current user has admin privileges
    print $person->getFirstname().' '.$person->getLastname().' ('.$person->getUsername().")\n";
}