#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);

require_once 'Sirprize/Basecamp/Milestone/Entity/Observer/Stout.php';
$entityObserverStout = new \Sirprize\Basecamp\Milestone\Entity\Observer\Stout();

require_once 'Sirprize/Basecamp/Milestone/Entity/Observer/Log.php';
$entityObserverLog = new \Sirprize\Basecamp\Milestone\Entity\Observer\Log();
$entityObserverLog->setLog($log);

$milestones = $basecamp->getMilestoneCollectionInstance();
$milestone = $milestones->getMilestoneInstance();
$milestone->attachObserver($entityObserverStout);
$milestone->attachObserver($entityObserverLog);

require_once 'Sirprize/Basecamp/Date.php';
$date = new \Sirprize\Basecamp\Date('2010-03-01');

require_once 'Sirprize/Basecamp/Id.php';
$projectId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_PROJECT_ID);
$userId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_USER_ID);

$milestone
	->setProjectId($projectId)
	->setResponsiblePartyId($userId)
	->setDeadline($date)
	->setTitle('Har Har Har')
	->setWantsNotification(true)
;

print ($milestone->create()) ? 'OK' : 'ERROR';