#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);

require_once 'Sirprize/Basecamp/TodolistItem/Collection/Observer/Stout.php';
$collectionObserverStout = new \Sirprize\Basecamp\TodolistItem\Collection\Observer\Stout();

require_once 'Sirprize/Basecamp/TodolistItem/Collection/Observer/Log.php';
$collectionObserverLog = new \Sirprize\Basecamp\TodolistItem\Collection\Observer\Log();
$collectionObserverLog->setLog($log);

require_once 'Sirprize/Basecamp/Id.php';
$id = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_TODOLISTITEM_ID);

$todolistItems = $basecamp->getTodolistItemCollectionInstance();
$todolistItems->attachObserver($collectionObserverStout);
$todolistItems->attachObserver($collectionObserverLog);
$todolistItem = $todolistItems->startById($id);

if($todolistItem === null)
{
	die("Not found\n");
}

if($todolistItems->getResponse()->isError())
{
	die("Error\n");
}

print "comments count: ".$todolistItem->getCommentsCount()."\n";
print "completed: ".$todolistItem->getIsCompleted()."\n";
print "completed at: ".$todolistItem->getCompletedAt()."\n";
print "completer id: ".$todolistItem->getCompleterId()."\n";
print "content: ".$todolistItem->getContent()."\n";
print "created at: ".$todolistItem->getCreatedAt()."\n";
print "creator id: ".$todolistItem->getCreatorId()."\n";
print "due at: ".$todolistItem->getDueAt()."\n";
print "id: ".$todolistItem->getId()."\n";
print "position: ".$todolistItem->getPosition()."\n";
print "todolist id: ".$todolistItem->getTodolistId()."\n";
print "completed on: ".$todolistItem->getCompletedOn()."\n";
print "created on: ".$todolistItem->getCreatedOn()."\n";