#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);

require_once 'Sirprize/Basecamp/TodolistItem/Collection/Observer/Stout.php';
$collectionObserverStout = new \Sirprize\Basecamp\TodolistItem\Collection\Observer\Stout();

require_once 'Sirprize/Basecamp/TodolistItem/Collection/Observer/Log.php';
$collectionObserverLog = new \Sirprize\Basecamp\TodolistItem\Collection\Observer\Log();
$collectionObserverLog->setLog($log);

require_once 'Sirprize/Basecamp/TodolistItem/Entity/Observer/Stout.php';
$entityObserverStout = new \Sirprize\Basecamp\TodolistItem\Entity\Observer\Stout();

require_once 'Sirprize/Basecamp/TodolistItem/Entity/Observer/Log.php';
$entityObserverLog = new \Sirprize\Basecamp\TodolistItem\Entity\Observer\Log();
$entityObserverLog->setLog($log);

require_once 'Sirprize/Basecamp/Id.php';
$todolistId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_TODOLIST_ID);

$todolistItems = $basecamp->getTodolistItemCollectionInstance();
$todolistItems->attachObserver($collectionObserverStout);
$todolistItems->attachObserver($collectionObserverLog);
$todolistItems->startByTodolistId($todolistId);

if($todolistItems->getResponse()->isError())
{
	die("Error\n");
}

foreach($todolistItems as $todolistItem)
{
	$todolistItem
		->attachObserver($entityObserverStout)
		->attachObserver($entityObserverLog)
		->setContent($todolistItem->getContent().' - 2')
		->update()
	;
}