#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

$basecamp = new \Sirprize\Basecamp\Cli($config);
$basecamp->setLog($log);

$timeEntryId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_TIMEENTRY_ID);

$timeEntries = $basecamp->getTimeEntriesInstance();
$timeEntry = $timeEntries->startById($timeEntryId);

if($timeEntry === null)
{
	die("Not found\n");
}

if($timeEntries->getResponse()->isError())
{
	die("Error\n");
}

print "id: ".$timeEntry->getId()."\n";
print "date: ".$timeEntry->getDate()."\n";
print "hours: ".$timeEntry->getHours()."\n";
print "description: ".$timeEntry->getDescription()."\n";