#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$projectId = new Id(BASECAMP_EXAMPLE_PROJECT_ID);

$timeEntries = $service->getTimeEntriesInstance();
$timeEntries->startAllByProjectId($projectId);

if($timeEntries->getResponse()->isError())
{
    die("Error\n");
}

foreach($timeEntries as $timeEntry)
{
    print "id: ".$timeEntry->getId()."\n";
    print "date: ".$timeEntry->getDate()."\n";
    print "hours: ".$timeEntry->getHours()."\n";
    print "description: ".$timeEntry->getDescription()."\n";
    print "--------------------------\n";
}