#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$timeEntryId = new Id(BASECAMP_EXAMPLE_TIMEENTRY_ID);

$timeEntries = $service->getTimeEntriesInstance();
$timeEntry = $timeEntries->startById($timeEntryId);

if($timeEntry === null)
{
    die("Not found\n");
}

if($timeEntries->getResponse()->isError())
{
    die("Error\n");
}

print "id: ".$timeEntry->getId()."\n";
print "date: ".$timeEntry->getDate()."\n";
print "hours: ".$timeEntry->getHours()."\n";
print "description: ".$timeEntry->getDescription()."\n";