#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;
use Sirprize\Basecamp\Comment\Collection;

$service = new Cli($config);
$service->setLog($log);

$milestoneId = new Id(BASECAMP_EXAMPLE_MILESTONE_ID);

$comments = $service->getCommentsInstance();
$comments->startAllByResourceId($milestoneId, Collection::RESOURCE_MILESTONE);

if($comments->getResponse()->isError())
{
    die("Error\n");
}

foreach($comments as $comment)
{
    print $comment->getBody().' - '.$comment->getId()."\n";
}