#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);
$todoLists = $basecamp->getTodoListsInstance();
$todoLists->findById(BASECAMP_EXAMPLE_TODOLIST_ID);

if($todoLists->getResponse()->isError())
{
	die('Error');
}

foreach($todoLists as $todoList)
{
	print 'id: '.$todoList->getId()."\n";
	print 'name: '.$todoList->getName()."\n";
	print 'project-id: '.$todoList->getProjectId()."\n";
	print 'milestone-id: '.$todoList->getMilestoneId()."\n";
	
	foreach($todoList->getItems() as $item)
	{
		print '>> id: '.$item->getId()."\n";
		print '>> todo-list-id: '.$item->getListId()."\n";
		print '>> content: '.$item->getContent()."\n";
	}
}