#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);
$items = $basecamp->getTodoListItemsInstance();
$items->findAllByTodoListId(BASECAMP_EXAMPLE_TODOLIST_ID);


if($items->getResponse()->isError())
{
	die('Error');
}

foreach($items as $item)
{
	print $item->getContent().' - '.$item->getId()."\n";
}