#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$todoLists = $service->getTodoListsInstance();
$todoLists->startAllByResponsibiltyParty('');

if($todoLists->getResponse()->isError())
{
    die("Error\n");
}

foreach($todoLists as $todoList)
{
    print $todoList->getName().' - '.$todoList->getId()."\n";

    if($todoList->getTodoItems())
    {
        foreach($todoList->getTodoItems() as $todoItem)
        {
            print ">> ".$todoItem->getContent()."\n";
        }
    }
}