#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);

require_once 'Sirprize/Basecamp/Todolist/Collection/Observer/Stout.php';
$collectionObserverStout = new \Sirprize\Basecamp\Todolist\Collection\Observer\Stout();

require_once 'Sirprize/Basecamp/Todolist/Collection/Observer/Log.php';
$collectionObserverLog = new \Sirprize\Basecamp\Todolist\Collection\Observer\Log();
$collectionObserverLog->setLog($log);

require_once 'Sirprize/Basecamp/Id.php';
$projectId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_PROJECT_ID);

$todolists = $basecamp->getTodolistCollectionInstance();
$todolists->attachObserver($collectionObserverStout);
$todolists->attachObserver($collectionObserverLog);
$todolists->startAllByProjectId($projectId);

if($todolists->getResponse()->isError())
{
	die('Error');
}

foreach($todolists as $todolist)
{
	print "name: ".$todolist->getName()." - ".$todolist->getId()."\n";
	print "--------------------------\n";
}