#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);

require_once 'Sirprize/Basecamp/TodoList/Collection/Observer/Stout.php';
$collectionObserverStout = new \Sirprize\Basecamp\TodoList\Collection\Observer\Stout();

require_once 'Sirprize/Basecamp/TodoList/Collection/Observer/Log.php';
$collectionObserverLog = new \Sirprize\Basecamp\TodoList\Collection\Observer\Log();
$collectionObserverLog->setLog($log);

require_once 'Sirprize/Basecamp/Id.php';
$id = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_TODOLIST_ID);

$todoLists = $basecamp->getTodoListsInstance();
$todoLists->attachObserver($collectionObserverStout);
$todoLists->attachObserver($collectionObserverLog);
$todoList = $todoLists->startById($id);

if($todoList === null)
{
	die("Not found\n");
}

if($todoLists->getResponse()->isError())
{
	die("Error\n");
}

print "completed count: ".$todoList->getCompletedCount()."\n";
print "description: ".$todoList->getDescription()."\n";
print "id: ".$todoList->getId()."\n";
print "milestone id: ".$todoList->getMilestoneId()."\n";
print "name: ".$todoList->getName()."\n";
print "position: ".$todoList->getPosition()."\n";
print "private: ".$todoList->getIsPrivate()."\n";
print "project id: ".$todoList->getProjectId()."\n";
print "tracked: ".$todoList->getIsTracked()."\n";
print "uncompleted count: ".$todoList->getUncompletedCount()."\n";
print "complete: ".$todoList->getIsComplete()."\n";


if($todoList->getTodoItems())
{
	foreach($todoList->getTodoItems() as $todoItem)
	{
		print ">> ".$todoItem->getContent()."\n";
	}
}