#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);

require_once 'Sirprize/Basecamp/Todolist/Collection/Observer/Stout.php';
$collectionObserverStout = new \Sirprize\Basecamp\Todolist\Collection\Observer\Stout();

require_once 'Sirprize/Basecamp/Todolist/Collection/Observer/Log.php';
$collectionObserverLog = new \Sirprize\Basecamp\Todolist\Collection\Observer\Log();
$collectionObserverLog->setLog($log);

require_once 'Sirprize/Basecamp/Id.php';
$id = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_TODOLIST_ID);

$todolists = $basecamp->getTodolistCollectionInstance();
$todolists->attachObserver($collectionObserverStout);
$todolists->attachObserver($collectionObserverLog);
$todolist = $todolists->startById($id);

if($todolist === null)
{
	die("Not found\n");
}

if($todolists->getResponse()->isError())
{
	die("Error\n");
}

print "completed count: ".$todolist->getCompletedCount()."\n";
print "description: ".$todolist->getDescription()."\n";
print "id: ".$todolist->getId()."\n";
print "milestone id: ".$todolist->getMilestoneId()."\n";
print "name: ".$todolist->getName()."\n";
print "position: ".$todolist->getPosition()."\n";
print "private: ".$todolist->getIsPrivate()."\n";
print "project id: ".$todolist->getProjectId()."\n";
print "tracked: ".$todolist->getIsTracked()."\n";
print "uncompleted count: ".$todolist->getUncompletedCount()."\n";
print "complete: ".$todolist->getIsComplete()."\n";


if($todolist->getTodoItems())
{
	foreach($todolist->getTodoItems() as $todolistItem)
	{
		print ">> ".$todolistItem->getContent()."\n";
	}
}