#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp/Cli.php';
$basecamp = new \Sirprize\Basecamp\Cli($config);
$basecamp->setLog($log);

$todoLists = $basecamp->getTodoListsInstance();
$todoLists->startAllByResponsibiltyParty('');

if($todoLists->getResponse()->isError())
{
	die("Error\n");
}

foreach($todoLists as $todoList)
{
	print $todoList->getName().' - '.$todoList->getId()."\n";
	
	if($todoList->getTodoItems())
	{
		foreach($todoList->getTodoItems() as $todoItem)
		{
			print ">> ".$todoItem->getContent()."\n";
		}
	}
}