#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

$service = new \Sirprize\Basecamp\Cli($config);
$service->setLog($log);

$todoLists = $service->getTodoListsInstance();
$todoList = $todoLists->getTodoListInstance();

$date = new \Sirprize\Basecamp\Date('2010-03-01');

$projectId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_PROJECT_ID);
$userId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_USER_ID);

$todoList
	->setProjectId($projectId)
	->setName('Har Har Har To To Tooo')
;

$todoList->create();