#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$projectId = new Id(BASECAMP_EXAMPLE_PROJECT_ID);

$milestones = $service->getMilestonesInstance();
$milestones->startAllByProjectId($projectId);

if($milestones->getResponse()->isError())
{
    die("Error\n");
}

foreach($milestones as $milestone)
{
    try {
        $milestone->delete();

        if($milestone->getResponse()->isError())
        {
            continue;
        }
    }
    catch(Exception $exception)
    {
        print $exception->getMessage()."\n";
        continue;
    }
}