#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);

require_once 'Sirprize/Basecamp/Milestone/Collection/Observer/Stout.php';
$collectionObserver = new \Sirprize\Basecamp\Milestone\Collection\Observer\Stout();

require_once 'Sirprize/Basecamp/Id.php';
$projectId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_PROJECT_ID);

$milestones = $basecamp->getMilestoneCollectionInstance();
$milestones->attachObserver($collectionObserver);
$milestones->startByProjectId($projectId);

if($milestones->getResponse()->isError())
{
	die('Error');
}

require_once 'Sirprize/Basecamp/Milestone/Entity/Observer/Stout.php';
$milestoneObserver = new \Sirprize\Basecamp\Milestone\Entity\Observer\Stout();

foreach($milestones as $milestone)
{
	try {
		$milestone->attachObserver($milestoneObserver);
		$milestone->delete();
		
		if($milestone->getResponse()->isError())
		{
			continue;
		}
	}
	catch(Exception $exception)
	{
		continue;
	}
}