#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

$service = new \Sirprize\Basecamp\Cli($config);
$service->setLog($log);

$projectId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_PROJECT_ID);

$milestones = $service->getMilestonesInstance();
$milestones->startAllByProjectId($projectId);

if($milestones->getResponse()->isError())
{
	die("Error\n");
}

foreach($milestones as $milestone)
{
	try {
		$milestone->delete();
		
		if($milestone->getResponse()->isError())
		{
			continue;
		}
	}
	catch(Exception $exception)
	{
		print $exception->getMessage()."\n";
		continue;
	}
}