#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;
use Sirprize\Basecamp\Milestone\Collection;

$service = new Cli($config);
$service->setLog($log);

$projectId = new Id(BASECAMP_EXAMPLE_PROJECT_ID);

$milestones = $service->getMilestonesInstance();
$milestones->startAllByProjectId($projectId, Collection::FIND_ALL);

if($milestones->getResponse()->isError())
{
    die("Error\n");
}

foreach($milestones as $milestone)
{
    print "comments count: ".$milestone->getCommentsCount()."\n";
    print "completed: ".$milestone->getIsCompleted()."\n";
    print "created on: ".$milestone->getCreatedOn()."\n";
    print "creator id: ".$milestone->getCreatorId()."\n";
    print "deadline: ".$milestone->getDeadline()."\n";
    print "id: ".$milestone->getId()."\n";
    print "project id: ".$milestone->getProjectId()."\n";
    print "responsible party id: ".$milestone->getResponsiblePartyId()."\n";
    print "responsible party type: ".$milestone->getResponsiblePartyType()."\n";
    print "title: ".$milestone->getTitle()."\n";
    print "wants notification: ".$milestone->getWantsNotification()."\n";
    print "--------------------------\n";
}