#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

$service = new \Sirprize\Basecamp\Cli($config);
$service->setLog($log);

$projectId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_PROJECT_ID);

$milestones = $service->getMilestonesInstance();
$milestones->startAllByProjectId($projectId, \Sirprize\Basecamp\Milestone\Collection::FIND_ALL);

if($milestones->getResponse()->isError())
{
	die("Error\n");
}

foreach($milestones as $milestone)
{
	print "comments count: ".$milestone->getCommentsCount()."\n";
	print "completed: ".$milestone->getIsCompleted()."\n";
	print "created on: ".$milestone->getCreatedOn()."\n";
	print "creator id: ".$milestone->getCreatorId()."\n";
	print "deadline: ".$milestone->getDeadline()."\n";
	print "id: ".$milestone->getId()."\n";
	print "project id: ".$milestone->getProjectId()."\n";
	print "responsible party id: ".$milestone->getResponsiblePartyId()."\n";
	print "responsible party type: ".$milestone->getResponsiblePartyType()."\n";
	print "title: ".$milestone->getTitle()."\n";
	print "wants notification: ".$milestone->getWantsNotification()."\n";
	print "--------------------------\n";
}