#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;
use Sirprize\Basecamp\Date;

$service = new Cli($config);
$service->setLog($log);

$milestones = $service->getMilestonesInstance();
$milestone = $milestones->getMilestoneInstance();

$date = new Date('2010-03-01');

$projectId = new Id(BASECAMP_EXAMPLE_PROJECT_ID);
$userId = new Id(BASECAMP_EXAMPLE_USER_ID);

$milestone
    ->setProjectId($projectId)
    ->setResponsiblePartyId($userId)
    ->setDeadline($date)
    ->setTitle('Har Har Har')
    ->setWantsNotification(true)
;

$milestone->create();