#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);

require_once 'Sirprize/Basecamp/Milestone/Collection/Observer/Stout.php';
$collectionObserver = new \Sirprize\Basecamp\Milestone\Collection\Observer\Stout();

require_once 'Sirprize/Basecamp/Id.php';
$projectId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_PROJECT_ID);

$milestones = $basecamp->getMilestoneCollectionInstance();
$milestones->attachObserver($collectionObserver);
$milestones->startByProjectId($projectId, \Sirprize\Basecamp\Milestone\Collection::FIND_ALL);

if($milestones->getResponse()->isError())
{
	die('Error');
}

foreach($milestones as $milestone)
{
	require_once 'Sirprize/Basecamp/Date.php';
	$deadline = new \Sirprize\Basecamp\Date('2010-08-17');
	
	require_once 'Sirprize/Basecamp/Milestone/Entity/Observer/Stout.php';
	$observer = new \Sirprize\Basecamp\Milestone\Entity\Observer\Stout();
	
	$milestone
		->setTitle('My New Title')
		->setDeadline($deadline)
		->attachObserver($observer)
		->update()
	;
}