#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

$service = new \Sirprize\Basecamp\Cli($config);
$service->setLog($log);

$projectId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_PROJECT_ID);

$milestones = $service->getMilestonesInstance();
$milestones->startAllByProjectId($projectId, \Sirprize\Basecamp\Milestone\Collection::FIND_ALL);

if($milestones->getResponse()->isError())
{
	die("Error\n");
}

foreach($milestones as $milestone)
{
	$deadline = new \Sirprize\Basecamp\Date('2010-08-17');
	
	$milestone
		->setTitle('My New Title')
		->setDeadline($deadline)
		->update()
	;
}