#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$sourceProjectId = new Id(BASECAMP_EXAMPLE_PROJECT_ID);
$targetProjectId = new Id(BASECAMP_EXAMPLE_PROJECT_TARGET_ID);

$projects = $service->getProjectsInstance();
$sourceProject = $projects->startById($sourceProjectId);

if($sourceProject === null)
{
    die("Source project not found\n");
}

if($projects->getResponse()->isError())
{
    die("Source project error\n");
}

$sourceProject->copy($targetProjectId);