#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp/Cli.php';
$basecamp = new \Sirprize\Basecamp\Cli($config);
$basecamp->setLog($log);

require_once 'Sirprize/Basecamp/Id.php';
$projectId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_PROJECT_ID);

$projects = $basecamp->getProjectsInstance();
$project = $projects->startById($projectId);

if($project === null)
{
	die("Not found\n");
}

if($projects->getResponse()->isError())
{
	die("Error\n");
}

$project->startSubElements();

foreach($project->getMilestones() as $milestone)
{
	print "(".$milestone->getId().") ".$milestone->getTitle()."\n";
	
	foreach($milestone->getTodoLists() as $todoList)
	{
		print "    (".$todoList->getId().") ".$todoList->getName()."\n";
		
		foreach($todoList->getTodoItems() as $todoItem)
		{
			print "        (".$todoItem->getId().") ".$todoItem->getContent()."\n";
		}
	}
	
	print "------------------------------\n";
}