#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$projectId = new Id(BASECAMP_EXAMPLE_PROJECT_ID);

$projects = $service->getProjectsInstance();
$project = $projects->startById($projectId);

if($project === null)
{
    die("Not found\n");
}

if($projects->getResponse()->isError())
{
    die("Error\n");
}

$project->startSubElements();

foreach($project->getMilestones() as $milestone)
{
    print "(".$milestone->getId().") ".$milestone->getTitle()."\n";

    foreach($milestone->getTodoLists() as $todoList)
    {
        print "    (".$todoList->getId().") ".$todoList->getName()."\n";

        foreach($todoList->getTodoItems() as $todoItem)
        {
            print "        (".$todoItem->getId().") ".$todoItem->getContent()."\n";
        }
    }

    print "------------------------------\n";
}