#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$projects = $service->getProjectsInstance();
$projects->startAll();

if($projects->getResponse()->isError())
{
    die("Error\n");
}

foreach($projects as $project)
{
    print $project->getName().' - '.$project->getId()."\n";
}