#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);

require_once 'Sirprize/Basecamp/Project/Collection/Observer/Stout.php';
$collectionObserverStout = new \Sirprize\Basecamp\Project\Collection\Observer\Stout();

require_once 'Sirprize/Basecamp/Project/Collection/Observer/Log.php';
$collectionObserverLog = new \Sirprize\Basecamp\Project\Collection\Observer\Log();
$collectionObserverLog->setLog($log);

require_once 'Sirprize/Basecamp/Id.php';
$projectId = new \Sirprize\Basecamp\Id(BASECAMP_EXAMPLE_PROJECT_ID);

$projects = $basecamp->getProjectCollectionInstance();
$projects->attachObserver($collectionObserverStout);
$projects->attachObserver($collectionObserverLog);
$project = $projects->startById($projectId);

if($project === null)
{
	die("Not found\n");
}

if($projects->getResponse()->isError())
{
	die("Error\n");
}

#print "announcement: ".$project->getAnnouncement()."\n";
print "created on: ".$project->getCreatedOn()."\n";
print "id: ".$project->getId()."\n";
print "last changed on: ".$project->getLastChangedOn()."\n";
print "name: ".$project->getName()."\n";
print "show announcement: ".$project->getShowAnnouncement()."\n";
print "show writeboards: ".$project->getShowWriteboards()."\n";
print "start page: ".$project->getStartPage()."\n";
print "status: ".$project->getStatus()."\n";
#print "company: ".$project->getCompany()."\n";