#!/usr/bin/env php
<?php

/**
 * Basecamp API Wrapper for PHP 5.3+ 
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt
 *
 * @category   Sirprize
 * @package    Basecamp
 * @subpackage Try
 * @copyright  Copyright (c) 2010, Christian Hoegl, Switzerland (http://sirprize.me)
 * @license    MIT License
 */

require_once '../_config.php';

require_once 'Sirprize/Basecamp.php';
$basecamp = new \Sirprize\Basecamp($config);

require_once 'Sirprize/Basecamp/Project/Collection/Observer/Stout.php';
$collectionObserverStout = new \Sirprize\Basecamp\Project\Collection\Observer\Stout();

require_once 'Sirprize/Basecamp/Project/Collection/Observer/Log.php';
$collectionObserverLog = new \Sirprize\Basecamp\Project\Collection\Observer\Log();
$collectionObserverLog->setLog($log);

$projects = $basecamp->getProjectCollectionInstance();
$projects->attachObserver($collectionObserverStout);
$projects->attachObserver($collectionObserverLog);
$projects->startAll();

if($projects->getResponse()->isError())
{
	die("Error\n");
}
	
foreach($projects as $project)
{
	print $project->getName().' - '.$project->getId()."\n";
}