#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$projectId = new Id(BASECAMP_EXAMPLE_PROJECT_ID);

$projects = $service->getProjectsInstance();
$project = $projects->startById($projectId);

if($project === null)
{
    die("Not found\n");
}

if($projects->getResponse()->isError())
{
    die("Error\n");
}

#print "announcement: ".$project->getAnnouncement()."\n";
print "created on: ".$project->getCreatedOn()."\n";
print "id: ".$project->getId()."\n";
print "last changed on: ".$project->getLastChangedOn()."\n";
print "name: ".$project->getName()."\n";
print "show announcement: ".$project->getShowAnnouncement()."\n";
print "show writeboards: ".$project->getShowWriteboards()."\n";
print "start page: ".$project->getStartPage()."\n";
print "status: ".$project->getStatus()."\n";
#print "company: ".$project->getCompany()."\n";