#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$commentId = new Id(BASECAMP_EXAMPLE_COMMENT_ID);

$comments = $service->getCommentsInstance();
$comment = $comments->startById($commentId);

if($comments->getResponse()->isError())
{
    die("Error\n");
}

print $comment->getBody().' - '.$comment->getId()."\n";

foreach($comment->getAttachments() as $attachment)
{
    print $attachment->getDownloadUrl()."\n";
}