#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$todoListId = new Id(BASECAMP_EXAMPLE_TODOLIST_ID);

$todoItems = $service->getTodoItemsInstance();
$todoItems->startAllByTodoListId($todoListId);

if($todoItems->getResponse()->isError())
{
    die("Error\n");
}

foreach($todoItems as $todoItem)
{
    $todoItem->delete();
}