#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$id = new Id(BASECAMP_EXAMPLE_TODOLISTITEM_ID);

$todoItems = $service->getTodoItemsInstance();
$todoItem = $todoItems->startById($id);

if($todoItem === null)
{
    die("Not found\n");
}

if($todoItems->getResponse()->isError())
{
    die("Error\n");
}

print "comments count: ".$todoItem->getCommentsCount()."\n";
print "completed: ".$todoItem->getIsCompleted()."\n";
print "content: ".$todoItem->getContent()."\n";
print "created at: ".$todoItem->getCreatedAt()."\n";
print "creator id: ".$todoItem->getCreatorId()."\n";
print "due at: ".$todoItem->getDueAt()."\n";
print "id: ".$todoItem->getId()."\n";
print "position: ".$todoItem->getPosition()."\n";
print "todoList id: ".$todoItem->getTodoListId()."\n";
print "created on: ".$todoItem->getCreatedOn()."\n";