#!/usr/bin/env php
<?php

/*
 * This file is part of the Basecamp Classic API Wrapper for PHP 5.3+ package
 *
 * (c) Christian Hoegl <chrigu@sirprize.me>
 */

require_once '../_config.php';

use Sirprize\Basecamp\Id;
use Sirprize\Basecamp\Cli;

$service = new Cli($config);
$service->setLog($log);

$todoItems = $service->getTodoItemsInstance();
$todoItem = $todoItems->getTodoItemInstance();

$todoListId = new Id(BASECAMP_EXAMPLE_TODOLIST_ID);
$responsiblePartyId = new Id(BASECAMP_EXAMPLE_USER_ID);

$todoItem
    ->setTodoListId($todoListId)
    ->setResponsiblePartyId($responsiblePartyId)
    ->setContent('Whoaaaa')
    ->setNotify(true)
    ->create()
;